# TODO: jasypt 로 인코딩 해야함
server:
  port: 10100
spring:
  application:
    name: gateway
domain:
  payment-url: http://localhost:10101
  stream-url: http://localhost:10102
  user-url: http://localhost:10103
jwt:
  secret: secret
  expiration: 3600
  refresh-expiration: 86400
  algorithm: HMAC256