# TODO: jasypt 로 인코딩 해야함
server:
  port: 10100
spring:
  application:
    name: gateway
domain:
  payment-url: http://localhost:10101
  stream-url: http://localhost:10102
  user-url: http://localhost:10103