server:
  port: 10104
spring:
  application:
    name: schedule
  threads:
    virtual:
      enabled: true
r2dbc:
  master:
    url: r2dbc:pool:postgresql://host.docker.internal:5432/cherhy
    username: postgres
    password: 1234
  slave:
    url: r2dbc:pool:postgresql://host.docker.internal:5432/cherhy
    username: postgres
    password: 1234