spring:
  application:
    name: user

r2dbc:
  master:
    url: r2dbc:pool:mysql://host.docker.internal:3333/beauty
    username: root
    password: 1234
  slave:
    url: r2dbc:pool:mysql://host.docker.internal:3333/beauty
    username: root
    password: 1234

axon:
  serializer:
    general: xstream
  axonserver:
    servers: localhost:8124